-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.0.6
    hooks:
    -   id: pyupgrade
