language: python
services: docker
env:
    - PYTHON=python2.7
    - PYTHON=python3.6
    - PYTHON=pypy
install: pip install virtualenv
script: make test test-docker_$PYTHON
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
